language = {
    'so': 'So language - Congo',
    'Afrikaans': 'Afrikaans',
    'العربية': 'Arabic',
    'беларуская': 'Belarusian',
    'Български език': 'Bulgarian',
    'বাংলা': 'Bengali',
    'Català': 'Catalan',
    'Čeština': 'Czech',
    'Cymraeg': 'Welsh',
    'Dansk': 'Danish',
    'Deutsch': 'German',
    'Ελληνικά': 'Greek',
    'English': 'English',
    'Esperanto': 'Esperanto',
    'Español': 'Spanish',
    'eesti keel': 'Estonian',
    'فارسی': 'Persian',
    'Suomi': 'Finnish',
    'Wikang Filipino': 'Filipino',
    'Français': 'French',
    'Gaeilge': 'Irish',
    'Gàidhlig': 'Scottish Gaelic',
    'Sprēkō Þiudiskō': '?',
    'עברית': 'Hebrew',
    'हिन्दी': 'Hindi',
    'Hrvatski': 'Croatian',
    'Magyar': 'Hungarian',
    'Bahasa Indonesia': 'Indonesian',
    'Íslenska': 'Icelandic',
    'Italiano': 'Italian',
    '日本語': 'Japanese',
    '한국어': 'Korean',
    'Lingua latina': 'Latin',
    'Lietuvių': 'Lithuanian',
    'Latviešu valoda': 'Latvian',
    'मराठी': 'Marathi',
    'بهاس ملايو': 'Kelantanese Malay',
    'Plattdüütsch': 'Low German',
    'Nederlands': 'Dutch',
    'Norsk': 'Norwegian',
    'ਪੰਜਾਬੀ': 'Punjabi language',
    'Polski': 'Polish',
    'Português brasileiro': 'Brazil Portuguese',
    'Português europeu': 'European Portuguese',
    'Khuzdul': 'Khuzdul - Tolkien',
    'Quenya': 'Quenya - Tolkien',
    'Română': 'Romanian',
    'Русский': 'Russian',
    'Sindarin': 'Sindarin - Tolkien',
    'Slovenčina': 'Slovak',
    'Slovenščina': 'Slovenian',
    'af Soomaali': 'Somali',
    'Shqip': 'Albanian',
    'српски': 'Serbian',
    'Svenska': 'Swedish',
    'Kiswahili': 'Swahili',
    'ไทย': 'Thai',
    'tlhIngan-Hol': 'Klingon',
    'Thermian': 'Thermian - Galaxy Quest',
    'Türkçe': 'Turkish',
    'українська': 'Ukrainian',
    'Bahasa Malaysia': 'Malaysian',
    'Tiếng Việt': 'Vietnamese',
    '中文': 'Chinese'
}
